apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "powergrid.fullname" . }}-discord"
type: Opaque
data:
  DISCORD_APPLICATION_ID: "{{ required "secrets.DISCORD_APPLICATION_ID is required" .Values.secrets.DISCORD_APPLICATION_ID | b64enc }}"
  DISCORD_PUBLIC_KEY: "{{ required "secrets.DISCORD_PUBLIC_KEY is required" .Values.secrets.DISCORD_PUBLIC_KEY | b64enc }}"
  DISCORD_BOT_TOKEN: "{{ required "secrets.DISCORD_BOT_TOKEN is required" .Values.secrets.DISCORD_BOT_TOKEN | b64enc }}"
  DISCORD_OAUTH_SECRET: "{{ required "secrets.DISCORD_OAUTH_SECRET is required" .Values.secrets.DISCORD_OAUTH_SECRET | b64enc }}"
  DISCORD_GUILD_ID: "{{ .Values.secrets.DISCORD_GUILD_ID | b64enc }}"
