apiVersion: v1
entries:
  powergrid:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-01-06T02:58:35.809777+08:00"
    description: Like nginx, but for Discord bots.
    digest: 05d4a44ca98dae182d9f4f1d022cb2cfbfa75e6a797fb2d95fb620699dce1c0c
    name: powergrid
    type: application
    urls:
    - https://sportshead.github.io/powergrid/powergrid-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2024-01-06T02:58:35.809505+08:00"
    description: Like nginx, but for Discord bots.
    digest: f0af74c80d38f3c89845a376fc82d0cccf52807110453acea5d1241d7830b5c9
    name: powergrid
    type: application
    urls:
    - https://sportshead.github.io/powergrid/powergrid-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-01-06T02:58:35.809066+08:00"
    description: Like nginx, but for Discord bots.
    digest: 428980ee77e7e3f8e1ed635c8ae5b0efa8239cdb30f2b7ed8249e2067bb4aeb9
    name: powergrid
    type: application
    urls:
    - https://sportshead.github.io/powergrid/powergrid-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-01-06T02:58:35.807023+08:00"
    description: Like nginx, but for Discord bots.
    digest: bed2edf5edf2536e87afca3c3119205536e4c9b6632d48ebab7df41c3905bf59
    name: powergrid
    type: application
    urls:
    - https://sportshead.github.io/powergrid/powergrid-0.1.0.tgz
    version: 0.1.0
generated: "2024-01-06T02:58:35.806197+08:00"
