apiVersion: v1
entries:
  powergrid:
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2024-01-03T16:34:20.839438+08:00"
    description: Like nginx, but for Discord bots.
    digest: f0af74c80d38f3c89845a376fc82d0cccf52807110453acea5d1241d7830b5c9
    name: powergrid
    type: application
    urls:
    - https://sportshead.github.io/powergrid/powergrid-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-01-03T16:34:20.839197+08:00"
    description: Like nginx, but for Discord bots.
    digest: 428980ee77e7e3f8e1ed635c8ae5b0efa8239cdb30f2b7ed8249e2067bb4aeb9
    name: powergrid
    type: application
    urls:
    - https://sportshead.github.io/powergrid/powergrid-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-01-03T16:34:20.838949+08:00"
    description: Like nginx, but for Discord bots.
    digest: bed2edf5edf2536e87afca3c3119205536e4c9b6632d48ebab7df41c3905bf59
    name: powergrid
    type: application
    urls:
    - https://sportshead.github.io/powergrid/powergrid-0.1.0.tgz
    version: 0.1.0
generated: "2024-01-03T16:34:20.838611+08:00"
