apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunbot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bunbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bunbot
    spec:
      containers:
        - name: bot
          image: ghcr.io/sportshead/powergrid-examples-bunbot:0.2.1
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "15m"
              memory: "48Mi"
            limits:
              cpu: "30m"
              memory: "96Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bunbot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bunbot
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bunbot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bunbot
  ports:
    - port: 80
      targetPort: http
      appProtocol: http
---
apiVersion: powergrid.sportshead.dev/v10
kind: Command
metadata:
  name: pingjs
spec:
  serviceName: bunbot
  command:
    name: pingjs
    description: Say hello to JavaScript!
    options:
      - name: name
        description: Who should we greet?
        type: 3
        required: false
---
apiVersion: powergrid.sportshead.dev/v10
kind: Command
metadata:
  name: sleep
spec:
  serviceName: bunbot
  shouldSendDeferred: true
  command:
    name: sleep
    description: zzzzzz!
    options:
      - name: time
        description: "Amount of time to sleep for (ms, default: 5000)"
        type: 4
        min_value: 0
        max_value: 60000 # 1 minute
        required: false
