apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: bunbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bunbot
    spec:
      containers:
        - name: bot
          image: ghcr.io/sportshead/powergrid-examples-bunbot:0.1.0
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: bunbot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bunbot
  ports:
    - port: 80
      targetPort: http
      appProtocol: http
---
apiVersion: powergrid.sportshead.dev/v10
kind: PowergridCommand
metadata:
  name: pingjs
spec:
  serviceName: bunbot
  command:
    name: pingjs
    description: Say hello to JavaScript!
    options:
      - name: name
        description: Who should we greet?
        type: 3
        required: false
