apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: commands.powergrid.sportshead.dev
spec:
  group: powergrid.sportshead.dev
  scope: Namespaced
  names:
    plural: commands
    singular: command
    kind: Command
  versions:
    - name: v10
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Command
          type: string
          description: Name of the Discord command
          jsonPath: .spec.command.name
        - name: Service
          type: string
          description: Name of the associated service
          jsonPath: .spec.serviceName
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                shouldSendDeferred:
                  description: Indicates whether to respond with an initial deferred message to Discord. If true, any response from the service will be ignored. Use the interaction token in the request to send follow up messages instead.
                  type: boolean
                serviceName:
                  type: string
                # https://raw.githubusercontent.com/discord/discord-api-spec/44f6253fbd183c5bba94dec50024fcd7fb83f7e7/specs/openapi.json
                # can't be parsed from the JSON, needs to be manually rewritten
                # k8s openapi subset is goofy
                command:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                  properties:
                    name:
                      type: string
                      minLength: 1
                      maxLength: 32
                    name_localizations:
                      type: object
                      additionalProperties:
                        type: string
                        minLength: 1
                        maxLength: 32
                      maxProperties: 34
                    description:
                      type: string
                      maxLength: 100
                    description_localizations:
                      type: object
                      additionalProperties:
                        type: string
                        minLength: 1
                        maxLength: 100
                      maxProperties: 34
                    options:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: integer
                            enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
                          name:
                            type: string
                            minLength: 1
                            maxLength: 32
                          name_localizations:
                            type: object
                            additionalProperties:
                              type: string
                              minLength: 1
                              maxLength: 32
                            maxProperties: 34
                          description:
                            type: string
                            minLength: 1
                            maxLength: 100
                          description_localizations:
                            type: object
                            additionalProperties:
                              type: string
                              minLength: 1
                              maxLength: 100
                            maxProperties: 34
                          required:
                            type: boolean
                          autocomplete:
                            type: boolean
                          choices:
                            type: array
                            items:
                              # hacky, because value needs to be string/int/double
                              x-kubernetes-preserve-unknown-fields: true
                              type: object
                              name:
                                type: string
                                minLength: 1
                                maxLength: 100
                              name_localizations:
                                type: object
                                additionalProperties:
                                  type: string
                                  minLength: 1
                                  maxLength: 100
                                maxProperties: 34
                            maxItems: 25
                          min_value:
                            type: number
                          max_value:
                            type: number
                          min_length:
                            type: integer
                            minimum: 0
                            maximum: 6000
                          max_length:
                            type: integer
                            minimum: 1
                            maximum: 6000
                          channel_types:
                            type: array
                            items:
                              type: integer
                              enum: [ 0, 1, 2, 3, 4, 5, 10, 11, 12, 13, 14, 15 ]
                          # sub-options are copy/pasted because yaml does not allow nesting of aliases
                          options:
                            type: array
                            items:
                              type: object
                              properties:
                                type:
                                  type: integer
                                  enum: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ]
                                name:
                                  type: string
                                  minLength: 1
                                  maxLength: 32
                                name_localizations:
                                  type: object
                                  additionalProperties:
                                    type: string
                                    minLength: 1
                                    maxLength: 32
                                  maxProperties: 34
                                description:
                                  type: string
                                  minLength: 1
                                  maxLength: 100
                                description_localizations:
                                  type: object
                                  additionalProperties:
                                    type: string
                                    minLength: 1
                                    maxLength: 100
                                  maxProperties: 34
                                required:
                                  type: boolean
                                autocomplete:
                                  type: boolean
                                choices:
                                  type: array
                                  items:
                                    # hacky, because value needs to be string/int/double
                                    x-kubernetes-preserve-unknown-fields: true
                                    type: object
                                    name:
                                      type: string
                                      minLength: 1
                                      maxLength: 100
                                    name_localizations:
                                      type: object
                                      additionalProperties:
                                        type: string
                                        minLength: 1
                                        maxLength: 100
                                      maxProperties: 34
                                  maxItems: 25
                                min_value:
                                  type: number
                                max_value:
                                  type: number
                                min_length:
                                  type: integer
                                  minimum: 0
                                  maximum: 6000
                                max_length:
                                  type: integer
                                  minimum: 1
                                  maximum: 6000
                                channel_types:
                                  type: array
                                  items:
                                    type: integer
                                    enum: [ 0, 1, 2, 3, 4, 5, 10, 11, 12, 13, 14, 15 ]
                              required:
                                - type
                                - name
                                - description
                            maxItems: 25
                        required:
                          - type
                          - name
                          - description
                      maxItems: 25
                    default_member_permissions:
                      type: integer
                      minimum: 0
                      maximum: 562949953421311
                    dm_permission:
                      type: boolean
                    type:
                      type: integer
                      enum: [1, 2, 3]
                  required:
                    - name
              required:
                - serviceName
                - command
