{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "powergrid.serviceAccountName" . }}
  labels:
    {{- include "powergrid.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "powergrid.fullname" . }}
  labels:
    {{- include "powergrid.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - powergrid.sportshead.dev
    resources:
      - commands
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "powergrid.fullname" . }}
  labels:
    {{- include "powergrid.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "powergrid.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "powergrid.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
